# Python base image
FROM python:3.11-slim

# Maintainer information
LABEL maintainer="mona.ashtari@bsc.es"
LABEL version="alpha2.0"
LABEL description="A Python tool for federated dataset unbalance checking"
LABEL image.version="alpha2.0"
LABEL image.source="https://gitlab.bsc.es/fl/eucaim-cdm-federated-unbalance"

ENV PYTHONUNBUFFERED=1

# Set defaults for build arguments
ARG USER_UID=1000
ARG USER_GID=1000

# Create non-root user and group, and prevent login
RUN groupadd -g $USER_GID eucaim && \
    useradd -r -u $USER_UID -g eucaim -d /home/eucaim -m -s /usr/sbin/nologin eucaim

# Install system dependencies (if needed)
RUN apt-get update && \
    apt-get install -y --no-install-recommends git gosu \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set working directory (placeholder, overridden at runtime)
WORKDIR /app

# Copy Python dependencies and install them
COPY ./app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code
COPY ./app/ /app/
COPY ./entrypoint.sh /app/entrypoint.sh

# Set any necessary executable permissions for non-root user
RUN chown -R root:root /app && chmod 755 /app/main.py /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["python", "main.py"]
